# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 04:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import yiyaweb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('application_type', models.CharField(choices=[('G', '\u666e\u901a\u7533\u8bf7'), ('U', '\u5927\u5b66\u7533\u8bf7'), ('C', '\u793e\u533a\u5b66\u9662\u7533\u8bf7'), ('H', '\u9ad8\u4e2d\u7533\u8bf7')], default='G', max_length=1)),
                ('stage', models.CharField(choices=[('W', '\u7b49\u5f85\u4ed8\u6b3e'), ('Y', '\u5df2\u4ed8\u6b3e'), ('T', '\u7b49\u5f85\u586b\u8868'), ('P', '\u51c6\u5907\u4e2d'), ('I', '\u6b63\u5728\u7533\u8bf7'), ('F', '\u5df2\u5b8c\u6210')], default='W', max_length=1)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('mother_name', models.CharField(blank=True, max_length=50)),
                ('US_tel', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]*$', '\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u7535\u8bdd\u53f7\u7801\u3002')])),
                ('CHINA_tel', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]*$', '\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u7535\u8bdd\u53f7\u7801\u3002')])),
                ('US_address', models.CharField(blank=True, max_length=100)),
                ('CHINA_address', models.CharField(blank=True, max_length=100)),
                ('current_school', models.CharField(blank=True, max_length=100)),
                ('current_school_start', models.DateField(blank=True, null=True)),
                ('current_school_end', models.DateField(blank=True, null=True)),
                ('current_visa_status', models.CharField(choices=[('N', '\u65e0'), ('F1I', 'F1\u5c31\u8bfb'), ('F1O', 'F1\u5f00\u9664'), ('B', 'B1/B2'), ('O', '\u5176\u4ed6')], default='N', max_length=5)),
                ('language_test', models.CharField(choices=[('Y', '\u96c5\u601d'), ('T', '\u6258\u798f'), ('C', 'College ENG101'), ('N', '\u65e0')], default='N', max_length=1)),
                ('language_score', models.FloatField(blank=True, null=True)),
                ('applying_college', models.CharField(blank=True, max_length=50)),
                ('applying_quater', models.CharField(choices=[('Sprint', '\u6625\u5b63\u5b66\u671f'), ('Summer', '\u590f\u5b63\u5b66\u671f'), ('Autumn', '\u79cb\u5b63\u5b66\u671f'), ('Winter', '\u51ac\u5b63\u5b66\u671f')], default='Spring', max_length=8)),
                ('applying_major', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_file', models.FileField(blank=True, null=True, upload_to=yiyaweb.models.passport_path)),
                ('visa_file', models.FileField(blank=True, null=True, upload_to=yiyaweb.models.visa_path)),
                ('current_score_file', models.FileField(blank=True, null=True, upload_to=yiyaweb.models.current_score_path)),
                ('I20_file', models.FileField(blank=True, null=True, upload_to=yiyaweb.models.I20_path)),
                ('previous_score_file', models.FileField(blank=True, null=True, upload_to=yiyaweb.models.previous_score_path)),
                ('language_test_file', models.FileField(blank=True, null=True, upload_to=yiyaweb.models.language_test_path)),
                ('bank_statement_file', models.FileField(blank=True, null=True, upload_to=yiyaweb.models.bank_statement_path)),
                ('other_file', models.FileField(blank=True, null=True, upload_to=yiyaweb.models.other_path)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]*$', '\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u7535\u8bdd\u53f7\u7801\u3002')])),
                ('description', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('R', 'Received'), ('P', 'Responsed'), ('C', 'Complete')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]*$', '\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u7535\u8bdd\u53f7\u7801\u3002')])),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('post_code', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9]*$', '\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u7535\u8bdd\u53f7\u7801\u3002')])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yiyaweb.Student'),
        ),
    ]
