# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yiyaweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='other_file',
        ),
    ]
