# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yiyaweb', '0005_application_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='application_name',
        ),
    ]
