# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yiyaweb', '0007_auto_20170626_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='email',
            new_name='application_email',
        ),
    ]
