# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yiyaweb', '0008_auto_20170627_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yiyaweb.Student'),
        ),
    ]
